#!/bin/sh
# /etc/init.d/led_clock

### BEGIN INIT INFO
# Provides:          led_clock
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the LED Clock Process
# Description:       This script will start and stop the LED Clock Service.
### END INIT INFO.

case "$1" in
  start)
    echo "Starting led_clock"
    /root/led_clock/ledclockworker &
    ;;
  stop)
    echo "Stopping led_clock"
    killall ledclockworker
    killall led_clock.py
    ;;
  *)
    echo "Usage: /etc/init.d/led_clock {start|stop}"
    exit 1
    ;;
esac

exit 0
